### ISSUE TITLE
Hit and Run Strategy Training stuck at non-optima for testing 

### ISSUE THREAD

**Issue by rickyyx** [gerrysonx/moba_env#1]
#### Map Configuration: 
```json
{
     "Restricted_x" : 400,
     "Restricted_y" : 400,
     "Restricted_w" : 200,
     "Restricted_h" : 200,
     "SelfHeroes" : [2007],
     "OppoHeroes" : [2006],
     "SpawnAreaWidth" : 100,
     "SelfTowers" : [], 
     "OppoTowers" : [], 
     "SelfCreeps" : [], 
     "OppoCreeps" : []
 }
```

#### Heros Configuration:
**2007**:
```
{
     "name" : "vayne",         
     "attackFreq" : 1,         
     "attackRange" : 100,
     "viewRange" : 2000,       
     "health" : 300,           
     "damage" : 100,           
     "speed" : 60,             
     "skills" : [-1, -1, -1, -1]
 }

```

**2006**:
```
{
     "name" : "lusian",        
     "attackFreq" : 1,         
     "attackRange" : 20,
     "viewRange" : 2000,       
     "health" : 1000,          
     "damage" : 100,           
     "speed" : 20,             
     "skills" : [-1, -1, -1, -1]
 }

```

#### Training Script: 
`python3 ppo.py` 

#### Description
It trains for 50 timestamps and converges at a `EpRewMean` of 1.4, but when rendered during test time, the two heroes would not attack each other.

**Comment by kumbayaco** [comment]
You may need change 'g_start_anew' to False , if you want to use the previous model

**Comment by kumbayaco** [comment]
Is gamecore stuck already or not ?

if not stuck, try change 'g_start_anew' to False if you want to use the previous trained model

**Comment by rickyyx** [comment]
Yes, I made a PR at my forked repo where you can replicate the above situation. 

https://github.com/githubxxcc/moba_env/pull/1

**Comment by rickyyx** [comment]
Never mind, I figure out why. 

Apparently it is expected that I manually control the enemy hero during test. 
https://github.com/gerrysonx/moba_env/blob/7225560388e753ae1baeb487242bf543eef6c4fe/gym_moba/gym_moba/envs/moba_multiplayer_env.py#L95-L102
